# Metadata
site_name: Reflex Icon Library
site_url: https://ril.celsiusnarhwal.dev
site_author: celsius narhwal

# Repository
repo_name: celsiusnarhwal/RIL
repo_url: https://github.com/celsiusnarhwal/RIL

# Navigation
nav:
  - Home: index.md
  - Font Awesome:
    - Font Awesome: fontawesome/index.md
    - Styling: fontawesome/styling.md
    - Font Awesome Pro: fontawesome/pro.md
    - Style Reference: fontawesome/style-reference.md
  - Simple Icons:
      - Simple Icons: simple/index.md
  - Material Symbols:
      - Material Symbols: material/index.md
  - Octicons:
      - Octicons: octicons/index.md
  - Phosphor:
      - Phosphor: phosphor/index.md
  - Bootstrap Icons:
      - Bootstrap Icons: bootstrap/index.md
  - Lucide:
      - Lucide: lucide/index.md

# Material for MkDocs
theme:
  name: material
  custom_dir: docs/.overrides
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple

    - media: "(prefers-color-scheme: light)"
      scheme: indigo
      primary: deep purple
      accent: deep purple

  font:
    text: Roboto
    code: Roboto Mono
    favicon: fontawesome/solid/book
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: fontawesome/solid/notes
      tip: material/lightbulb-on
      danger: material/fire
      code: fontawesome/solid/code

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - privacy:
      links_attr_map:
        target: _blank
  - typeset
  - iconoclast:
      uv: true
      css: true
  - social
  - artwall

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      options:
        custom_icons:
          - docs/.overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: celsiusnarhwal
      repo: RIL
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Additional Settings
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/celsiusnarhwal
      name: github.com/celsiusnarhwal
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/reflex-icon-library
      name: The Reflex Icon Library on PyPI
    - icon: simple/bluesky
      link: https://bsky.app/profile/celsiusnarhwal.dev
      name: bsky.app/profile/celsiusnarhwal.dev
    - icon: fontawesome/solid/envelope
      link: mailto:hello@celsiusnarhwal.dev
      name: hello@celsiusnarhwal.dev
    - icon: celsius
      link: https://celsiusnarhwal.dev
      name: celsiusnarhwal.dev
  generator: false
  annotate:
    toml: [.s2]

extra_css:
  - assets/stylesheets/admonitions.css
