[project]
name = "reflex-icon-library"
description = "Thousands of icons for any Reflex project"
readme = "README.md"
authors = [
    { name = "celsius narhwal", email = "hello@celsiusnarhwal.dev" }
]
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
    "casefy>=0.1.7",
    "decorator>=5.2.1",
    "deepmerge>=2.0",
    "esprima>=4.0.1",
    "inflect>=7.4.0",
    "jinja2>=3.1.4",
    "json5>=0.12.0",
    "loguru>=0.7.2",
    "packaging>=25.0",
    "pydantic>=2.10.0",
    "pydantic-extra-types>=2.10.0",
    "pydantic-settings>=2.6.1",
    "reflex>=0.8.0",
    "semver>=3.0.2",
    "yarl>=1.18.0",
]

[project.urls]
Homepage = "https://ril.celsiusnarhwal.dev"
Repository = "https://github.com/celsiusnarhwal/RIL"
Issues = "https://github.com/celsiusnarhwal/RIL/issues"
Changelog = "https://github.com/celsiusnarhwal/RIL/blob/main/CHANGELOG.md"

[dependency-groups]
docs = [
    "artwall",
    "cairosvg>=2.7.1",
    "fontawesomepro>=6.6.0",
    "iconoclast>=3.0.1",
    "mkdocs-material",
    "pillow>=11.0.0",
]

[tool.ruff.lint]
ignore = ["F403"]
extend-select = ["I"]

[tool.ruff.format]
docstring-code-format = false

[tool.pdm.version]
source = "scm"

[tool.uv.sources]
mkdocs-material = { git = "https://github.com/squidfunk/mkdocs-material-insiders" }
artwall = { git = "https://github.com/celsiusnarhwal/artwall" }

[[tool.uv.index]]
name = "fontawesome"
url = "https://fa.celsiusnarhwal.dev/simple"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
