name: Broken Icon
description: Report an icon that should be working, but isn't.
labels:
  - bug
  - broken-icon
assignees:
  - celsiusnarhwal

body:
  - type: checkboxes
    attributes:
      label: Before you begin...
      description: Please acknowledge the following statements.
      options:
        - label: I have searched this repository for similar issues.
          required: true
        - label: I'm not reporting a broken [Font Awesome](https://ril.celsiusnarhwal.dev/fontawesome) icon (there's a [separate issue template](https://github.com/celsiusnarhwal/RIL/issues/new?template=01-fontawesome.yml) for that).
          required: true
        - label: I'm not reporting a broken [Lucide](https://ril.celsiusnarhwal.dev/lucide) icon ([open an issue with Reflex](https://github.com/reflex-dev/reflex/issues) instead).
        - label: The icon exists in the respective upstream icon library.
          required: true
        - label: I'm following RIL's [documentation](https://ril.celsiusnarhwal.dev) with regards to the spelling and casing of icon names.
          required: true
        - label: I have reinstalled my project's frontend packages with `reflex init && reflex run` and the icon still isn't working.
          required: true

  - type: dropdown
    attributes:
      label: Icon Library
      description: Which library are you reporting a broken icon for?
      options:
        - Simple Icons
        - Material Symbols
        - Octicons
        - Phosphor
        - Bootstrap Icons
    validations:
      required: true

#  - type: markdown
#    attributes:
#      value: |
#        > [!NOTE]
#        > Issues related to [Lucide](https://ril.celsiusnarhwal.dev/lucide) are issues with Reflex itself and belong in [Reflex's repository](https://github.com/reflex-dev/reflex/issues).

  - type: input
    attributes:
      label: Icon Name
      description: | 
        Provide the exact name of the problematic icon as it appears on the upstream library's website. 
        
        - [Simple Icons](https://simpleicons.org)
        - [Material Symbols](https://fonts.google.com/icons)
        - [Octicons](https://primer.style/octicons)
        - [Phosphor](https://phosphoricons.com)
        - [Bootstrap Icons](https://icons.getbootstrap.com)
        
        <br>
    validations:
      required: true

  - type: input
    attributes:
      label: Which version of RIL are you using?
      description: You can find out by running `pip show reflex-icon-library` in your project's virtual environment. This works regardless of what tools you are or aren't using to manage your project's dependencies.
    validations:
      required: true

  - type: input
    attributes:
      label: Which version of Reflex are you using?
      description: You can find out by running `pip show reflex` in your project's virtual environment. This works regardless of what tools you are or aren't using to manage your project's dependencies.
    validations:
      required: true

  - type: input
    attributes:
      label: Which version of Python are you using?
      description: You can find out by running `python --version` in your project's virtual environment.
    validations:
      required: true

  - type: input
    attributes:
      label: Minimal Reproducible Example
      description: Provide a link to a public Git repository containing a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your issue. This isn't required, but your issue is likely to be resolved a lot faster if you do it.

  - type: textarea
    attributes:
      label: Other Details
      description: Provide any other details you think might be helpful.
