name: Bug
description: Report a bug that isn't a broken icon.
labels:
  - bug
assignees:
  - celsiusnarhwal

body:
  - type: checkboxes
    attributes:
      label: Before you begin...
      description: Please acknowledge the following statements.
      options:
        - label: I have searched this repository for similar issues.
          required: true
        - label: I've read and am following RIL's [documentation](https://ril.celsiusnarhwal.dev).
          required: true
        - label: I'm not reporting a broken icon. Broken icons should be reported using the [broken icon form](https://github.com/celsiusnarhwal/RIL/issues/new?assignees=celsiusnarhwal&labels=bug%2Cbroken-icon&projects=&template=00-icon.yml&title=%5BBroken+Icon%5D%3A+).
          required: true

  - type: textarea
    attributes:
      label: Description
      description: Describe the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Describe how to reproduce the bug. Please be detailed.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Result
      description: Describe what *should* happen after following the steps you described above.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Result
      description: Describe what *actually* happens after following the steps you described above.
    validations:
      required: true

  - type: input
    attributes:
      label: Which version of RIL are you using?
      description: You can find out by running `pip show reflex-icon-library` in your project's virtual environment. This works regardless of what tools you are or aren't using to manage your project's dependencies.
    validations:
      required: true

  - type: input
    attributes:
      label: Which version of Reflex are you using?
      description: You can find out by running `pip show reflex` in your project's virtual environment. This works regardless of what tools you are or aren't using to manage your project's dependencies.
    validations:
      required: true

  - type: input
    attributes:
      label: Which version of Python are you using?
      description: You can find out by running `python --version` in your project's virtual environment.
    validations:
      required: true

  - type: input
    attributes:
      label: Minimal Reproducible Example
      description: Provide a link to a public Git repository containing a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your issue. This isn't required, but your issue is likely to be resolved a lot faster if you do it.
