name: Docs (Experimental)

on:
  workflow_dispatch:


jobs:
  build:
    name: Bulid Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Git Credentials
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://username:${{ secrets.GH_PAT }}@github.com

      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set Up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: 0.5.x
          enable-cache: true

      - name: Install Dependencies
        run: uv sync --only-group docs
        env:
          UV_INDEX: ${{ secrets.FONTAWESOME_INDEX_URL }}

      - name: Deploy to Vercel
        uses: celsiusnarhwal/mkdocs-vercel-deploy@main
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-name: reflex-icon-library
          production: true