on:
  push:
    paths:
      - docs/**
      - mkdocs.yml
      - pyproject.toml
      - .github/workflows/docs.yml

  workflow_dispatch:


jobs:
  build:
    name: Bulid Documentation
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Set Up Git Credentials
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://${{ github.repository_owner}}/${{ secrets.GH_PAT }}@github.com

      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Set Up uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - run: git clone https://github.com/squidfunk/mkdocs-material-insiders

      - name: Install Python
        run: uv python install

      - name: Install Dependencies
        run: uv sync --only-group docs

      - name: Build Documentation
        run: uv run icl install && uv run mkdocs build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site

  deploy:
    name: Deploy Documentation
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: site
          path: site

      - name: Deploy to Vercel
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --yes --prod
        working-directory: site
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
