name: Release

on:
  release:
    types:
      - published


jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Set Up Git Credentials
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://username:${{ secrets.GH_PAT }}@github.com

      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set Up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: 0.5.x
          enable-cache: true

      - name: Install Python
        run: uv python install

      - name: Build Package
        run: uv build --no-sources

      - name: Publish Package
        run: uv publish

